dist: trusty
sudo: required
language: bash
env:
 - PACKER_V=1.3.1 TF_V=0.11.10 TFLINT_V=0.7.2 ANS_V=2.7.1 ANSLINT_V=3.5.1
before_install:
 - curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-09/run.sh | bash
 - sudo pip install --upgrade pip
install:
 - |
   if [ `uname -m` = x86_64 ]; then
     #packer
     wget https://releases.hashicorp.com/packer/${PACKER_V}/packer_${PACKER_V}_linux_amd64.zip -O packer.zip
     sudo unzip packer.zip -d /usr/bin
     #TF
     wget https://releases.hashicorp.com/terraform/${TF_V}/terraform_${TF_V}_linux_amd64.zip -O tf.zip
     sudo unzip tf.zip -d /usr/bin
     #TFLINT
     wget https://github.com/wata727/tflint/releases/download/v0.7.2/tflint_linux_amd64.zip -O tflint.zip
     sudo unzip tflint.zip -d /usr/bin
     #ans&ans-lint
   else 
     #packer
     wget https://releases.hashicorp.com/packer/${PACKER_V}/packer_${PACKER_V}_linux_i386.zip -O packer.zip
     sudo unzip packer.zip -d /usr/bin
     #TF
     wget https://releases.hashicorp.com/terraform/${TF_V}/terraform_${TF_V}_linux_i386.zip -O tf.zip
     sudo unzip tf.zip -d /usr/bin
     #TFLINT
     wget https://github.com/wata727/tflint/releases/download/v0.7.2/tflint_linux_i386.zip -O tflint.zip
     sudo unzip tflint.zip -d /usr/bin
     #ans&ans-lint
   fi 
 - sudo pip install ansible==${ANS_V} ansible-lint==${ANSLINT_V}
 - echo $PATH
before_script:
 - touch ~/.ssh/appuser ~/.ssh/appuser.pub
 - mv packer/variables.json.example packer/variables.json
 - mv terraform/terraform.tfvars.example terraform/terraform.tfvars
 - mv terraform/stage/terraform.tfvars.example terraform/stage/terraform.tfvars
 - mv terraform/prod/terraform.tfvars.example terraform/prod/terraform.tfvars
script:
  # packer
 - cd ${TRAVIS_BUILD_DIR}/packer
 - packer validate -var-file=variables.json ubuntu16.json
 - packer validate -var-file=variables.json immutable.json
 - cd ${TRAVIS_BUILD_DIR}
 - packer validate packer/app.json
 - packer validate packer/db.json
 # tf && tflint
 - cd ${TRAVIS_BUILD_DIR}/terraform
 - cd ${TRAVIS_BUILD_DIR}/terraform/stage
 - terraform init -backend=false && terraform validate && tflint
 - cd ${TRAVIS_BUILD_DIR}/terraform/prod
 - terraform init -backend=false && terraform validate && tflint
 # ansible-lint
 - cd ${TRAVIS_BUILD_DIR}/ansible
 - ansible-lint playbooks/*.yml  --exclude=roles/jdauphant.nginx

notifications:
  slack:
    rooms:
      secure: IFVmH3RMyp8Ju75CBciDmaEsy9vNqSfOMPEj1kiKCf4ol2datCqSQ4GQFdPM/tCl/DMOr2c28KpUzt62tH/HVt//WyOxRjKARbqsNYxZl1ViNZIPLDNSHskSsg4qm+HTW3xn8TYhrpbd9wEmyltsphmbacv/2L+BzK5/4Z4AhpkSpMo4lM0CuDoL6LpNGk7gWYmyEDNpW42gAl2fELSrezjLdTPlzSLU4YDRj0EKTs8vn1awg3i/YDWMV8ao9pdjtf/yuY6T5B697Up0Jj/LBIevuC6kUJUAowTsbwx9ilYcUqeRROtwKc9zD4mYKM0xORcppxJWJdn5Z2bwq4/cfdx1OfxhfQIxrM0BPUQZWkCyd/yvIVDp3dtWWP4FcFFQIb9Qi8m//ML3kbgkbfS9i3jlyRmYwdGnZCt+9e3QMSq1lP0F/CDNQ56Kh2qjScm0yrqKJKLKtt2gZeoUT1+Dc2JUFixDuLDtFQ4tyIEdrxi0TF7fPwzYxwcyJ5lk+8Eti5b2zBeefhcW4TASG7Ve11oTXHIfb2JEJmxdf1+lA8PZnBrZ5an/M2q3pFk0xZ72za8l/yQkIpT3YMvHMCRLgM5JBj+JzI3koSrgLMi5UaiNy5pYobro0EOpLTXefatTXGSYNAyvVOEPuhwvVe4XDXuQ9V/06bZpwr6wm97sIuo=
