---
- name: Install Ruby
  hosts: all
  become: true
  tasks:
    - name: Install required packages
      apt:
       name:
        - ruby-full
        - ruby-bundler
        - build-essential
       state: present
       autoclean: yes

